### ISSUE TITLE
Should New Proteus Sites include a LICENSE file?

### ISSUE THREAD

**Issue by reshleman** [thoughtbot/proteus#13]
It looks like both the `proteus-middleman` and `proteus-jekyll` repositories* include a `LICENSE.md` file file that's copied into new sites when using the Proteus generator.

It makes sense that the repositories contain a LICENSE, since they're open-source. I wonder, however, whether this file should be excluded from newly-generated sites, since it may not be the user's intention to release a generated site under the MIT License.

I would propose that `Proteus::Kit#new` should remove the `LICENSE.md` file after cloning the appropriate kit repo, but before creating initial git commit.

Happy to submit a PR if this is of interest.

`*` The `proteus-gulp` repo does not contain a `LICENSE.md` file -- not sure whether this is intentional or simply an oversight.

**Comment by joshuaogle** [comment]
You're absolutely right. The LICENSE files have been removed from the kits and I'm now linking to a shared license from the README. Editing the README is one of the first things that people update, so I think that's easier than going in and removing it programatically. Thanks for bringing this up!
