### ISSUE TITLE
Unable to find matching thoughtbot kit repo

### ISSUE THREAD

**Issue by timup** [thoughtbot/proteus#15]
Still experiencing behavior similar to #9.

``` bash
$ proteus new middleman your-project-name
A thoughtbot repo doesn't exist with that name
```

replicating kit.rb 'new' method (https://github.com/thoughtbot/proteus/blob/master/lib/proteus/kit.rb#L17)

``` ruby
irb(main):001:0> system 'git ls-remote https://github.com/thoughtbot/proteus-middleman.git > /dev/null 2>&1'
=> true
```

not sure where/why this breaks during execution. Have tested with 'jekyll' as an argument to `proteus new` with the same results.

Local internet connection is good.  GitHub is good.

**Comment by joshuaogle** [comment]
@timup What OS are you running? It definitely sounds like it's something in the script, and that might help narrow it down. Most of our testing has been on OS X and Linux

**Comment by timup** [comment]
OSX El Cap 10.11.3

**Comment by timup** [comment]
in ruby shell
```ruby
require 'proteus'
@p = Proteus::Kit.new
@p.new('middleman','spec/dummy')
```
returns
```ruby
A thoughtbot repo doesn't exist with that name
```

**Comment by joshuaogle** [comment]
There is a lot changing in that code in #14, so I'm hoping that already fixes this problem, but I will make sure to have a developer look it over to see if they can tell what might have been happening. Thanks for all the info!

**Comment by timup** [comment]
Awesome, thanks!

**Comment by timup** [comment]
@joshuaogle: I know it's WIP, but built the gem from the dev branch and still get funky behavior:

```bash
$ proteus new middleman
Can't find a repo at git@github.com:thoughtbot/proteus-middleman.git.
```

following the script, it seems to break when the repo is accessed using ssh here:
https://github.com/thoughtbot/proteus/blob/jo-list-repos/lib/proteus/kit.rb#L37 

changing the url at this point to https, L37 returns true and the script continues.

**Comment by joshuaogle** [comment]
Yep, those should have been https. I've updated it, but I'm not sure if that will fix your issue. We have a few people that know a lot about Git shell scripts, so I'll have them take a look

**Comment by artsheeps** [comment]
Unfortunately I'm facing the same problem... `A thoughtbot repo doesn't exist with that name`

**Comment by joshuaogle** [comment]
@artsheeps #14 Is finally merged and there is now a version 0.4 on RubyGems. The issue should be resolved now, but I'll leave it open if you wouldn't mind updating to confirm.

**Comment by GitHub-Mike** [comment]
Same problem with proteus-kits-0.4 + Ruby22-x64 + Windows 7 - 64bit:
`proteus new jekyll projectname`
`Can't find a repo at https://github.com/thoughtbot/proteus-jekyll.git`

**Comment by tysongach** [comment]
This project is no longer being actively maintained.
