### ISSUE TITLE
proteus server Coffeescript error

### ISSUE THREAD

**Issue by bretonio** [thoughtbot/proteus#17]
Running `proteus new jekyll jekyll-project` and then  `proteus server` in the root directory yields

```bash
Starting the server
Configuration file: /home/bretonio/Jekyll-Projects/jekyll-semantico/_config.yml
Configuration file: /home/bretonio/Jekyll-Projects/jekyll-semantico/_config.yml
            Source: source
       Destination: build
 Incremental build: disabled. Enable with --incremental
      Generating... 
[31m                    uninitialized constant CoffeeScript[0m
[31m  Liquid Exception: uninitialized constant CoffeeScript in /_layouts/default.html [0m
jekyll 3.3.1 | Error:  uninitialized constant CoffeeScript
```

The same result from running `jekyll serve -w` as instructed in the README.md.

Is this the line referred to in the error message regarding _layouts/default.html?

```
<script type="text/javascript" src="{% asset_path application.js %}"></script>
```
There is an `application.coffee` in the `_assets folder` but no `application.js` anywhere in the project. But editing this value does not alter the outcome.

The Proteus kit for Middleman? Purrs like a kitten right out of the box.

**Comment by tysongach** [comment]
This project is no longer being actively maintained.
