### ISSUE TITLE
A Hugo starter kit? 

### ISSUE THREAD

**Issue by rdwatters** [thoughtbot/proteus#18]
I mean, if you're taking suggestions for SSGs, Hugo is the fastest out there. There are a few Hugo starter kits  around GH, but netlify did an especially good job with "Victor Hugo":

https://github.com/netlify/victor-hugo

And you can see here (and in many other places throughout the forum) that starter-kit-type pointers are common threads:

https://discuss.gohugo.io/t/livereload-problems-when-serving-hugo-and-webpack-theme-at-same-time/5237/4

**Comment by tysongach** [comment]
Hi @rdwatters!

We built the Middleman and Jekyll kits simply because it is what we use most here at thoughtbot. We don’t have any one using Hugo, so creating and maintaining a kit is not something we’re interested in at this time.
