### ISSUE TITLE
Automatically remove thoughtbot's git remote as origin

### ISSUE THREAD

**Issue by cllns** [thoughtbot/proteus#6]
On the [**proteus-middleman** page](https://github.com/thoughtbot/proteus-middleman#getting-started), it has a note about removing the remote origin, since that's linked to thoughtbot's GitHub repo.

Could something like that happen automatically when running `proteus new`? 

A few options I can foresee:
A
---
1. Remove the thoughtbot `origin` remote

2. Prompt the user for their repo URL 

3. a) If they supply one, add that URL as `origin`
    b) If they don't, show a note about how they can later run `git remote add origin` and leave the repo without a remote

B
---
1. Prompt the user for their repo URL 

2. a) If they supply one, change origin to that URL
    b) If they don't, keep origin as thoughtbot

C
---
1. Rename the remote from `origin` to `thoughtbot` or `upstream`

2. Prompt the user for their repo URL

3. Same as A - 3

My preference is for **C** (then **A**, then **B**)

Happy to do the work, if this is the direction you'd like to go!

**Comment by cllns** [comment]
Just thought of another option... It's quite different from the other three.

D
---

1. Still deliver the template via `git clone` 
2. Remove the .git folder inside the directory they cloned to
3. Run `git init` 

This gives the user the benefit of having a clean history. If they want to add their own remote, they can. Actually step 3 is optional, since they don't necessarily even need to use git.

This is my new first preference!

**Comment by joshuaogle** [comment]
Right now we have option A as part of the `proteus setup` command on each repo (except without the note), but I do think it might be better as part of `proteus new`.

C does sound like a good idea and I like that it isn't destructive. It seems like pulling in changes later is pretty likely to cause conflicts since most of the files in the generators are meant to be changed. And if they intended to contribute, they would have just cloned instead of using the gem. Thoughts on that?

**Comment by cllns** [comment]
I agree that not many people will be wanting to pull in changes, since it will cause conflicts.

Further in that direction... what do you think of **D**? I added it shortly before your last comment, so maybe you didn't see it.

It would relegate `git clone` to be merely the delivery method. 

And it would even further split up (i) people who are contributing to the project and (ii) people who are using the application. This is more inline other OSS development where you have to explicitly clone and fork the repo if you want to contribute, and the rest of the users aren't bothered with it.

**Comment by joshuaogle** [comment]
I nearly went with *D* when setting it up in `proteus setup`, but just collapsed commits instead. I think just nuking the `.git` directory does solve some issues (I wasn't able to collapse commits if they weren't running setup from the master branch, and you would still have a Proteus contributor as the author of the initial commit).

I was afraid D felt more like a sledgehammer, but it looks like that's what we need.

:+1: Sounds good to me. Feel free to make a PR, or I'll get to it next week

**Comment by cllns** [comment]
Just made this PR: #7

Also, I'd like to state my preference for running `setup` with `new` automatically. Either just running `setup` after `new`, or even renaming `new` to `clone` (or another name) and making `new` a meta-command that runs `clone` then `setup`.

When I made a new project with `proteus` I didn't even think to run `setup` after `new`, as evidenced by my making this PR without knowing about `setup`.

**Comment by joshuaogle** [comment]
Merged #7
