### ISSUE TITLE
'A thoughtbot repo doesn't exist with that name'

### ISSUE THREAD

**Issue by nicksturkenboom** [thoughtbot/proteus#9]
Hi, when I'm following your instructions on a windows 8.1 machine I get the following message after initiating a new project:

$ proteus new middleman my-project-name
DL is deprecated, please use Fiddle
The system cannot find the path specified.
A thoughtbot repo doesn't exist with that name

Any idea what I'm doing wrong?

**Comment by joshuaogle** [comment]
That usually just means that it doesn't see the repo on Github. You have the command right, and it does work for me. Is it possible you didn't have an internet connection at the time? Or something may have been wrong with Github.

Could you try again? I can do some testing to see if it is a Windows issue, but it sounds like a connection problem.

**Comment by nicksturkenboom** [comment]
Hmm, I do have connection with github, other files have no trouble installing, it just seems to be Proteus specifically I'm afraid.

**Comment by mrlee-io** [comment]
Must be a windows problem, I just ran the generator last night on OS X and all was groovy.

Sadly I haven't installed ruby on my Windows machine and don't really want to.

**Comment by nicksturkenboom** [comment]
Don't even try, it's a nightmare, really. Just a few more days before I can start working on a linux machine..

**Comment by Steviant** [comment]
I'm getting the same error on OS X Yosemite, so it's not isolated to Windows.

Literally copy-pasted the commands from http://thoughtbot.github.io/proteus/ to test, seeing this output:

```
$ gem install proteus-kits
Fetching: proteus-kits-0.2.gem (100%)
Successfully installed proteus-kits-0.2
Parsing documentation for proteus-kits-0.2
Installing ri documentation for proteus-kits-0.2
Done installing documentation for proteus-kits after 0 seconds
1 gem installed

[New shell opened]

$ proteus new middleman your-project-name
A thoughtbot repo doesn't exist with that name
```

Cloning the repos directly works fine, though.

**Comment by lifecoderua** [comment]
Just got the same issue on Ubuntu with a freshly installed gem. I have check the code, it has the same problem as the standalone kit instructions: it try to clone with the `git@github.com..` url instead of the public `https://github.com..` one.

As a result it checks the user permissions even if he only try to check out the repo:
```
Permission denied (publickey).
fatal: Could not read from remote repository.
```
